### ISSUE TITLE
slider: Cannot move handles when they are stacked (min === max)

### ISSUE THREAD

**Issue by Shipow** [algolia/instantsearch.js#1040]
![bug-slider](https://cloud.githubusercontent.com/assets/976175/15608986/90f8d572-241d-11e6-952f-9363a975dac9.gif)

**Comment by pixelastic** [comment]
Shouldn't it belong to https://github.com/instantsearch/instantsearch-ion.rangeSlider?

**Comment by Shipow** [comment]
this is not the ion slider but default IS one

**Comment by vvo** [comment]
In the tourism example, we solved that by doing:

```css
    .ais-range-slider--handle-lower {
      transform: translateX(-50%);
    }
    
    .ais-range-slider--handle-upper {
      transform: translateX(50%);
    }
```

I wonder if we should do that by default, thoughts?
