### ISSUE TITLE
CurrentRefinements: More specific BEM style

### ISSUE THREAD

**Issue by Kikobeats** [algolia/instantsearch.js#1580]
Currently I'm fighting with CurrentFilters styles. This is how it looks:

<img width="281" alt="screen shot 2016-11-18 at 14 23 27" src="https://cloud.githubusercontent.com/assets/2096101/20431505/96c4312a-ad9a-11e6-997c-20c03386b88c.png">

and the code:

```scss
.ais-CurrentRefinements__item:not(.ais-CurrentRefinements__itemParent) {
  @extend .dib, .br4, .mb2, .mr2, .mt3, .bg-light-blue, .near-white;
}

.ais-CurrentRefinements__itemParent > .ais-CurrentRefinements__itemLabel {
  display: block;
  @extend .mt3;
}

.ais-CurrentRefinements__itemLabel {
  @extend .pa0, .pl2;
}

.ais-CurrentRefinements__itemClear {
  background: none;
  border: none;
  padding: 0.5rem 0.5rem 0.4rem 0.5rem;

  @extend .v-mid, .pointer;

  > svg {
    @extend .br-100, .blue, .f6, .dim;
    padding: 2px;
    background-color: white;
    vertical-align: baseline !important;
  }
}
```

As you can see, the code don't look plain. It could be easy fix adding the correctly specific class, like:

```css
.ais-CurrentRefinements__item:not(.ais-CurrentRefinements__itemParent
```

It actually refers the item selected, then need a `ais-CurrentRefinements__itemSelected` class.

```css
.ais-CurrentRefinements__itemParent > .ais-CurrentRefinements__itemLabel
```

It actually refers the facet name, then need `ais-CurrentRefinements__itemsName` class.
