### ISSUE TITLE
cssunminifier makes dist/instantsearch.css breaks all css if minified

### ISSUE THREAD

**Issue by cmalard** [algolia/instantsearch.js#2375]
https://github.com/algolia/instantsearch.js/blob/613a6155228d38accab4560ec18da852e08f59fd/scripts/build.sh#L10
It makes all the code after background-image unusable. Just ran into this, quite surprising.
```css
 .ais-search-box--powered-by-link{background-image:url('data:image/svg+xml;utf8,<svg></svg>');vertical-align:middle;}
```
is converted to:
```css
 .ais-search-box--powered-by-link {
    background-image: url('data:image/svg+xml;
    utf8, <svg></svg>');
    vertical-align: middle;
}
```
https://mrcoles.com/blog/css-unminify/
if it is re-minified:
```css
 .ais-search-box--powered-by-link{image:url('data:image/svg+xml;
utf8,<svg></svg>');vertical-align:middle;}
```
Cf. https://github.com/mrcoles/cssunminifier/issues/2

**Bug: What browsers are impacted? Which versions?**
All?

**What is the version you are using? Always use the latest one before opening a bug issue.**
Latest: 2.1.4
