### ISSUE TITLE
`debug.css` theme

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#249]
Just a crazy idea I quickly hacked to help me debug BEM classes added. It adds an outline to every class starting with `ais-` and also display the name of the class when we hover it.

![debugcss](https://cloud.githubusercontent.com/assets/283419/10511570/5cc6a2e6-733a-11e5-9905-d2961f60f3a2.gif)

Here is the current code:

```css
[class^=ais-] {
  outline: 1px solid red !important;
  position:relative;
}
[class^=ais-]:hover:after {
  position:absolute;
  content:attr(class);
  background: grey;
  color: black;
  padding:0.5rem;
  font-size:1rem;
  top:0;
  white-space: nowrap;
  z-index:10;
  background:red;
  left:0;
  height:20px;
}
[class^=ais-] [class^=ais-] {
  outline: 1px solid orange !important;
  position:relative;
}
[class^=ais-] [class^=ais-]:hover:after {
  z-index:100;
  background: orange;
  top:20px;
}
[class^=ais-] [class^=ais-] [class^=ais-] {
  outline: 1px solid yellow !important;
  position:relative;
}
[class^=ais-] [class^=ais-] [class^=ais-]:hover:after {
  z-index:1000;
  background: yellow;
  top:40px;
}
```

Maybe that is something we'd provide to theme creators, to help them see which class is used where.
