### ISSUE TITLE
tourism example: Unable to get results if price range is narrowed before query

### ISSUE THREAD

**Issue by pixelastic** [algolia/instantsearch.js#642]
I first do a narrow search on the price range, then do a search query. After that the map is centered somewhere (?) and I cannot move the price range anymore.

![2015-11-17_16h00m42](https://cloud.githubusercontent.com/assets/283419/11215108/eb906326-8d44-11e5-8d8e-43351f28b6e7.gif)

Not sure if this is an example issue or a price range one.

https://community.algolia.com/instantsearch.js/examples/tourism/

**Comment by bobylito** [comment]
@vvo isn't that an implementation bug in the widget? How to solve that?

**Comment by vvo** [comment]
Yes most probably an issue in the rangeSlider widget indeed. Did not have a look.

**Comment by bobylito** [comment]
I can reproduce the same wrong behavior by pushing one of the handle on top of the other.

**Comment by bobylito** [comment]
One fix that I see: prevent the handles to overlap. We can do a CSS though : 
```css
.ais-range-slider--handle-lower {
  transform: translateX(-50%);
}
.ais-range-slider--handle-upper {
  transform: translateX(50%);
}
```
